apiVersion: v1
kind: Service
metadata:
  name: testrail
  labels:
    app: testrail
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app: testrail
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: testrail
  labels:
    app: testrail
spec:
  selector:
    matchLabels:
      octopusexport: OctopusExport
  replicas: 1
  serviceName: testrail-bs-svc
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: OrderedReady
  template:
    metadata:
      labels:
        app: web
        octopusexport: OctopusExport
    spec:
      containers:
        - name: testrail
          image: voilatiel/testrail
